import React from 'react'

//matadate 
export const metadata = {
  title: 'Create About page',
  description: 'Generated by create next app',
}

export default function About() {
  return (
    <div className='m-24'>About Page</div>
  )
}
