import NavbarComponent from '@/components/NavBarComponent'
import './globals.css'
import { Inter } from 'next/font/google'
import FooterComponent from '@/components/FooterComponent'
const inter = Inter({ subsets: ['latin'] })


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">      
      <body className={inter.className}>
        <NavbarComponent/>
        {children}
        <FooterComponent/>
      </body>
    </html>
  )
}
